import passport from "passport";
import { Strategy as GoogleStrategy } from "passport-google-oauth20";
import dotenv from "dotenv";
import db from "./db.js";

dotenv.config();

const googleClientId = process.env.CLIENT_ID;
const googleClientSecret = process.env.CLIENT_SECRET;

passport.use(
  new GoogleStrategy(
    {
      clientID: googleClientId,
      clientSecret: googleClientSecret,
      callbackURL: `/auth/google/redirect`,
    },
    async (accessToken, refreshToken, profile, done) => {
      try {
        db.query(
          "SELECT * FROM Users WHERE googleId = ?",
          [profile.id],
          (err, results) => {
            if (err) {
              return done(err);
            }
            if (results.length > 0) {
              // User found
              return done(null, results[0]);
            } else {
              // User not found, create new user
              const newUser = {
                user_id: null, // Auto-generated by MySQL
                name: profile.displayName,
                email: profile.emails[0].value,
                is_admin: false,
                googleId: profile.id,
              };

              db.query(
                "INSERT INTO Users (name, email, googleId, is_admin) VALUES (?, ?, ?, ?)",
                [
                  newUser.name,
                  newUser.email,
                  newUser.googleId,
                  newUser.is_admin,
                ],
                (err, result) => {
                  if (err) {
                    return done(err);
                  }
                  newUser.user_id = result.insertId;
                  return done(null, newUser);
                }
              );
            }
          }
        );
      } catch (error) {
        return done(error);
      }
    }
  )
);

passport.serializeUser((user, done) => {
  done(null, user.user_id);
});

passport.deserializeUser((id, done) => {
  db.query("SELECT * FROM Users WHERE user_id = ?", [id], (err, results) => {
    if (err) {
      return done(err);
    }
    done(null, results[0]);
  });
});

export default passport;
